version: '3.6'
services:
  api:
    image: node:12.13-alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on: 
      - mysql
    command: sh -c "yarn && yarn dev:server"
  mysql:
    image: mysql:5.6
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_DATABASE: goomer
      MYSQL_ROOT_PASSWORD: passwd 
    ports:
      - 3306:3306