enum AppErrorTypes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RECORD_NOT_EXISTS = 'RECORD_NOT_EXISTS',
  MANDATORY_FIELD_NOT_SENT = 'MANDATORY_FIELD_NOT_SENT',
}

export default AppErrorTypes;
